### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by vanphandinh** [Khezen/docker-postgres#18] opened 2021-03-09 07:00 UTC
`NOTE: Configuring authentication for SERVER mode.

Traceback (most recent call last):
  File "run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 98, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 380, in create_app
    paths.init_app(app)
  File "/pgadmin4/pgadmin/utils/paths.py", line 103, in init_app
    raise InternalServerError(
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The user does not have permission to read and write to the specified storage directory.
[2021-03-09 06:51:14 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2021-03-09 06:51:14 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
[2021-03-09 06:51:14 +0000] [1] [INFO] Using worker: threads
[2021-03-09 06:51:14 +0000] [89] [INFO] Booting worker with pid: 89
[2021-03-09 06:51:16 +0000] [89] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/venv/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 98, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 380, in create_app
    paths.init_app(app)
  File "/pgadmin4/pgadmin/utils/paths.py", line 103, in init_app
    raise InternalServerError(
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The user does not have permission to read and write to the specified storage directory.
[2021-03-09 06:51:16 +0000] [89] [INFO] Worker exiting (pid: 89)
[2021-03-09 06:51:17 +0000] [1] [INFO] Shutting down: Master
[2021-03-09 06:51:17 +0000] [1] [INFO] Reason: Worker failed to boot.
[2021-03-09 06:51:21 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2021-03-09 06:51:21 +0000] [1] [INFO] Listening at: http://[::]:80 (1)
[2021-03-09 06:51:21 +0000] [1] [INFO] Using worker: threads
[2021-03-09 06:51:21 +0000] [82] [INFO] Booting worker with pid: 82
[2021-03-09 06:51:23 +0000] [82] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/venv/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 98, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 380, in create_app
    paths.init_app(app)
  File "/pgadmin4/pgadmin/utils/paths.py", line 103, in init_app
    raise InternalServerError(
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The user does not have permission to read and write to the specified storage directory.
[2021-03-09 06:51:23 +0000] [82] [INFO] Worker exiting (pid: 82)
[2021-03-09 06:51:23 +0000] [1] [INFO] Shutting down: Master
[2021-03-09 06:51:23 +0000] [1] [INFO] Reason: Worker failed to boot.`

**Comment by vanphandinh** [comment] 2021-03-09 07:41
<img width="715" alt="Screen Shot 2021-03-09 at 2 41 25 PM" src="https://user-images.githubusercontent.com/13887599/110435382-890b0900-80e5-11eb-8771-d640a6b168e9.png">

**Comment by vanphandinh** [comment] 2021-03-09 07:43
From pgAdmin4 docs:

**/var/lib/pgadmin** - This is the working directory in which pgAdmin stores session data, user files, configuration files, and it’s configuration database. Mapping this directory onto the host machine gives you an easy way to maintain configuration between invocations of the container.
**/pgadmin4/servers.json** - If this file is mapped, server definitions found in it will be loaded at launch time. This allows connection information to be pre-loaded into the instance of pgAdmin in the container. Note that server definitions are only loaded on first launch, i.e. when the configuration database is created, and not on subsequent launches using the same configuration database.
pgAdmin runs as the **pgadmin** user (**UID: 5050**) in the **pgadmin** group (**GID: 5050**) in the container. You must ensure that all files are readable, and where necessary (e.g. the working/session directory) for this user on the host machine. 

Fix: `sudo chown -R 5050:5050 pg_storage`

**Comment by jaybcee** [comment] 2021-03-09 21:59
Please pull and let me know if this works 

https://github.com/jaybcee/compose-postgres

I was able to reproduce the problem in WSL2 Linux on Windows, but can confirm that the current master works fine on Windows and Mac.

**Comment by jaybcee** [comment] 2021-03-10 00:45
@khezen this is caused by the change i made in #17. I believe its not a bad idea to revert it back to what it was prior and allow people to expand (as they already are with their numerous forks). This isn't really an issue, but it may add a layer of complexity.  As the BDFL, please suggest what you would prefer.

**Comment by khezen** [comment] 2021-03-10 07:18
Hi. I was able to reproduce on Fedora. Reverting your changes did not help. I'm looking into this.

**Comment by vanphandinh** [comment] 2021-03-10 07:20
Why don’t use my solution?
`sudo chown -R 5050:5050 pg_storage`

**Comment by khezen** [comment] 2021-03-10 07:48
Fixed in #19

**Closed as completed by khezen** 2021-03-10 07:48 UTC
